- README.md
- src/assets/js/languageSelector.js
- src/assets/stylesheets/extensions/_alert.scss
- src/assets/stylesheets/extensions/_select2.scss
- src/assets/stylesheets/main.scss
- src/sdk-reference/index/get-auto-refresh.md
- src/sdk-reference/index/refresh-internal.md
- src/sdk-reference/index/refresh.md
- src/sdk-reference/index/set-auto-refresh.md
* Add alert-box styles
* Fix markdown render in HTML text when `<code>` isn't in a supported SDKs languages
* Alert : https://deploy-preview-12--doc-v2.netlify.com/sdk-reference/index/get-auto-refresh/
* MD render : https://deploy-preview-12--doc-v2.netlify.com/sdk-reference/bulk/import/
* Little css enhancement on language-selector
> Update frontend render

- scaffolding/templates/action.go.md
- scaffolding/templates/action.js.md
- scaffolding/templates/index.md
- scaffolding/templates/usage-snippets/usage.java
In Javascript we care more about how the promise will resolve or reject (and what it will resolve/reject) than the return value.  
This PR replace the `Return` section by `Resolve` and `Reject` in the scaffolding tool.
- Remove Exception section for Go
- Replace the default Return section by Resolve and Reject for Javascript
- Add default order so metalsmith will use alphabetical order by default
> Add resolve and reject to js template

- src/sdk-reference/cpp/1/kuzzle/add-listener/index.md
- src/sdk-reference/cpp/1/kuzzle/add-listener/snippets/add-listener.cpp
- test/templates/without-connect.tpl.cpp
This PR update the c++ snippet to use c++11 lambda instead of listener class.  
- Step 1 : Run cpp tests: `bash run-snippet-tests.sh -n -p src/sdk-reference/cpp/1`
> KZL 495 - Update c++ snippet with lambda

- scaffolding/lib/utils.js
This is just a small pr to use GOPATH env var to check go function signatures.
> use GOPATH for go signatures

- index.js
Without this fix, pages with the same `order` value are displayed at random (for this purpose, an arbitrary large order value was already attributed to pages without one).
Instead, the sort should fall back to title values if 2 pages have the same order value.
Before:
After:
> sort by title if page orders are equal

- src/assets/stylesheets/_config.scss
- src/assets/stylesheets/layout/_nav.scss
- src/assets/stylesheets/libs/prism.css
- src/templates/partials/navMobile.html
- src/templates/partials/nav_sdk.html
Before : 
After : 
https://deploy-preview-60--kuzzle-doc-v2.netlify.com/sdk-reference/js/6/essentials/
* fix version and languages selector on mobile
* remove display none css rules for "Usage" snippets 
* change inline code background color for a more lighter one
> Fix left nav on sdk pages when section has no parent

- src/api/1/errors/index.md
Migration of the [API errors](https://docs.kuzzle.io/api-documentation/errors/) documentation. This requires a review as I modified/corrected a few error descriptions.
> API migration: error documentation

- src/assets/stylesheets/_config.scss
- src/assets/stylesheets/base/_typeset.scss
Just a tiny litle enhancement ! As discussed with the team, we wanted inline-blockquotes style to be more lighter.
Before : 
And now :
> Change inline-blockquotes style to a more lighter one

- src/api/1/kuzzle-response/index.md
Migrates and rewrites the Kuzzle response API documentation. Original documentation: https://docs.kuzzle.io/api-documentation/kuzzle-response/
> API migration: Kuzzle Response documentaiton

- src/api/1/controller-server/admin-exists/index.md
- src/api/1/controller-server/get-all-stats/index.md
- src/api/1/controller-server/get-config/index.md
- src/api/1/controller-server/get-last-stats/index.md
- src/api/1/controller-server/get-stats/index.md
- src/api/1/controller-server/index.md
- src/api/1/controller-server/info/index.md
- src/api/1/controller-server/now/index.md
Migration of the server controller documentation into the new documentation system.
See the netlify preview.
The way controller actions are documented has been changed, and it now follows this template:
```
<"Added in vXX.YY.ZZ" tag>
<Action description>
---
<HTTP query documentation>
<JSON query documentation>
---
[## Arguments (new section)]
<Required arguments documentation>
[### Optional:]
<Optional arguments documentation>
---
[## Body properties (new section)]
<Required body properties documentation>
[### Optional]
<Optional body properties documentation>
---
<Detailed response documentation, instead of having it embedded into response examples (new)>
<Response example, cleaned from unnecessary "documentation">
```
* `Arguments` and `Body properties` are separated sections because I …
> API migration: server controller

- src/sdk-reference/index.md
- src/sdk-reference/js/5/essentials/index.md
> Fix dead link for sdk js 5 and make sdk js 6 default sdk

- src/api/1/query-syntax/index.md
Complete rewrite of the following documentation section: https://docs.kuzzle.io/api-documentation/query-syntax/
Expected improvements:
* HTTP:
* optional headers are now documented 
* content type `multipart/form-data` is now fully documented
* Other protocols:
* define what "other protocols" are
* document the universally required `controller` and `action` parameters
* document the universally optional `jwt`, `requestId` and `volatile` parameters
Overall, I expect this new documentation to be clearer than our current one.
> API Query Syntax documentation

- src/sdk-reference/js/6/collection/search-specifications/snippets/search-specifications.js
Fix the failing test on collection.searchSpecifications because now the results are stored in a SearchResult object, instead of being directly returned (at least that's what I inferred from the code I read)
> [sdk/js/6] fix "collection.searchSpecifications" test template

- .ci/docker-compose.yml
Without this configuration, ES fails to start on servers with stricter limits (ES is part of the Kuzzle stack needed to test code examples).
> Tests stack: add a ulimit configuration to match ES prereqs

- src/assets/stylesheets/layout/_content.scss
- src/assets/stylesheets/layout/_search.scss
- src/assets/stylesheets/layout/_sidebar.scss
Set middle content column margin and reduce little bit sidebar width to fit 80 chars in code blocks
https://deploy-preview-96--kuzzle-doc-v2.netlify.com/sdk-reference/js/6/auth/check-token/
Check the signature, there is no more horizontal scrollbar.
Add css overflow rules to the right menu to disable horizontal scrolling
> KZL-738 Set middle content column margin to fit 80 chars in code blocks

- .travis.yml
Use Travis `script` provider instead of `s3` to allow to `--delete` on deployments
You can only check `.travis.yml` syntax
> [ci] Use script provider for s3 sync --delete

- src/assets/stylesheets/layout/_sidebar.scss
Add CSS rule to indent ToC childrens on right sidebar menu
https://deploy-preview-104--kuzzle-doc-v2.netlify.com/sdk-reference/js/6/kuzzle/add-listener/
> KZL-746 Add rules to indent ToC childrens

- run-snippet-tests.sh
This PR updates the test script to not attempt to push the test reports to s3 automatically so it can be used on dev.
> [dev] do not try to push to s3 on dev

- src/assets/stylesheets/base/_typeset.scss
* remove the useless `<code>` margin, which was only applied to non-link code, causing alignment problems
* fix the `<pre>` tag, currently forcing both the background and the font color to `white`, making this tag useless
> Fix code CSS

- src/api/1/controller-memory-storage/del/index.md
Add the missing `# del` title at the beginning of the [ms:del](https://docs-v2.kuzzle.io/api/1/controller-memory-storage/del/) documentation
> [API] Add missing ms:del documentation title

- README.md
- test/lib/helpers/logger.js
- test/lib/runners/baseRunner.js
To make examples clearer, or because of rich outputs, there are code snippets that need to output multiple lines of information.
This PR adds the possibility to the current system to test outputs on multiple lines. To make it work, just use the YAML format for multiple values.
For instance, here is a snippet on another branch (currently under development):
```js
try {
await kuzzle.ms.set('key', 'foobar');
// Prints: 26
console.log(await kuzzle.ms.bitcount('key'));
// Prints: 4
console.log(await kuzzle.ms.bitcount('key', {start: 0, end: 0}));
} catch (error) {
console.error(error.message);
}
```
As the snippet states, there are 2 outputs.
This snippet can now be tested using the following syntax:
```yaml
expected:
- 26
- 4
```
Also, if there are multiple outputs, then the code in this PR …
> SDK snippets: add the ability to test multiple outputs

- package-lock.json
- package.json
Replace the official [metalsmith-watch](https://www.npmjs.com/package/metalsmith-watch) with a custom version, able to handle the large number of files of our new documentation.
This change should hopefully be temporary, as a PR has been submitted to the official metalsmith-watch repo: https://github.com/FWeinb/metalsmith-watch/pull/44
If the PR stays unmerged for too long, then we should probably create our own, forked version of metalsmith-watch on NPM.
> Use a custom, more robust metalsmith-watch

- index.js
- package-lock.json
- package.json
- plugins/anchors.js
Adapts the metalsmith-watcher configuration, using the new dynamic directory keyword feature added in https://github.com/FWeinb/metalsmith-watch/pull/45 and the multi-target support added in https://github.com/FWeinb/metalsmith-watch/pull/46
This makes the watcher trigger a rebuild only on relevant files, instead of rebuilding the entire documentation everytime something has changed. 
Also, this PR disables uglify's compression in dev mode, as it takes a lot of times for no gain.
> Speed up rebuilds triggered by the watcher

- .ci/comment.html
- .travis.yml
Because we flush docs-v2.kuzzle.io when deploying.
It is not a safe place for snippets reports anymore.
Fix travis build stages order.
> [kuttlefish] Use dl.kuzzle.io to store reports

- index.js
Add algolia metas automatically only if page is the last children in ancestry (only for build process of course).
Moreover it allows us to optimize the number of requests to algolia
> [build] Add algolia metas automatically

- src/sdk-reference/cpp/1/auth/get-my-rights/snippets/get-my-rights.cpp
:warning: depends on https://github.com/kuzzleio/sdk-cpp/pull/42 :warning: 
Since the last C++ SDK update, the `user_rights*` structure created in the C++ SDK by the `auth:getMyRight` API call is now correctly freed. 
This cause another problem, since a vector is returned by that method, referencing pointers from the now deallocated structure. This dangling pointers problem causes random crashes whenever one tries to access the value returned by `auth:getMyRight`, as done in the C++ code example for that API method.
This problem has been resolved in this PR: https://github.com/kuzzleio/sdk-cpp/pull/42
This documentation PR updates the C++ example, as the type of the value returned by `auth:getMyRight` has changed.
> Update the getMyRights C++ snippet to the new C++ SDK version

- src/sdk-reference/js/6/events/index.md
:warning: depends on https://github.com/kuzzleio/sdk-javascript/pull/340
Following https://github.com/kuzzleio/sdk-javascript/pull/340, the `discarded` event returns the discarded request and not an error.
> JSv6 - discarded event

- src/sdk-reference/cpp/1/auth/get-current-user/index.md
- src/sdk-reference/cpp/1/auth/get-current-user/snippets/get-current-user.cpp
- src/sdk-reference/cpp/1/auth/get-my-rights/index.md
- src/sdk-reference/cpp/1/auth/get-my-rights/snippets/get-my-rights.cpp
- src/sdk-reference/cpp/1/auth/update-self/index.md
- src/sdk-reference/cpp/1/auth/update-self/snippets/update-self.cpp
- src/sdk-reference/cpp/1/auth/update-self/snippets/update-self.test.yml
- src/sdk-reference/cpp/1/search-result/index.md
- src/sdk-reference/cpp/1/user-right/index.md
- src/sdk-reference/cpp/1/user/content/index.md
- src/sdk-reference/cpp/1/user/id/index.md
- src/sdk-reference/cpp/1/user/index.md
- src/sdk-reference/cpp/1/user/intro/index.md
- src/sdk-reference/cpp/1/user/profile_ids/index.md
- src/sdk-reference/cpp/1/websocket/index.md
The latest C++ experimental release introduced a few breaking changes in the `auth` methods signatures.
The following documentations and their corresponding code snippets have been updated:
* `auth:getCurrentUser` does not return a `kuzzle_user*` pointer anymore, but a `User` class instance
* `auth:getMyRights` now returns a vector of `std::unique_ptr<UserRight>` pointers
* `auth:updateSelf` now return a `User` class instance instead of a `kuzzle_user*` pointer
The following core classes have been added to the documentation:
* `User`
* `UserRight`
* The changed methods have had their documentation updated to the latest documentation format.
* All core classes documentations now share the same order number, to let the doc builder sort these sections alphabetically in the separator
> Update snippets to the latest C++ SDK version

- config/webpack.js
- index.js
- package.json
Since the Javascript bundling has been moved to webpack, documentation rebuilds were very slow.
This is due to the uglifier plugin, which is very useful in production to reduce the size of the bundle, but makes the documentation hot reload a burden in dev mode.
This PR deactives the uglifier plugin in dev mode. This reduce the rebuild time from 6-9s on my machine to 150-300ms.
Add the `./config` directory to the eslint scope, and fix the linter errors.
> Fix the documentation rebuild time in development mode

- src/sdk-reference/cpp/1/auth/get-my-rights/snippets/get-my-rights.cpp
:warning: depends on https://github.com/kuzzleio/sdk-cpp/pull/46 (the CI *will fail* until the dependency is merged and the SDK deployed)
https://github.com/kuzzleio/sdk-cpp/pull/46 changes the return type of `auth:getMyRight` for the C++ SDK. 
This PR update the corresponding code snippet to match that change.
> [C++ SDK] update the auth:getMyRight return type

- src/guide/1/essentials/installing-kuzzle/index.md
Fix a few minor issues with the Kuzzle install documentation:
* fix the wrong title level for the manual install section, preventing it from appearing in the table of content
* fix the backquote markdown tag being erroneously used inside an alert paragraph
* fix a couple wording issues
> Fix manual installation section

- src/api/1/controller-security/search-users/index.md
The `body` lacked of the `query` field
> Fixed `body` in searchUsers API example

- src/sdk-reference/js/6/websocket/constructor/index.md
Documents https://github.com/kuzzleio/sdk-javascript/pull/364
Also updates the websocket documentation page format to our latest standard, and sort the options list in alphabetical order.
> Javascript SDK: websocket http headers option documentation

- src/plugins/1/essentials/hooks/index.md
- src/plugins/1/essentials/pipes/index.md
Change the way we pass functions to plugins pipes, hooks and action.  
Now we pass functions instead of function name on the plugin object.
See https://github.com/kuzzleio/kuzzle/pull/1227
- Step 1 :
- Step 2 :
- Step 3 :  
...
> Pass function to hooks, pipes and actions

- package-lock.json
- src/sdk-reference/cpp/1/document/search/index.md
- src/sdk-reference/cpp/1/document/search/snippets/search.cpp
- src/sdk-reference/cpp/1/kuzzle/add-listener/index.md
- src/sdk-reference/cpp/1/kuzzle/add-listener/snippets/add-listener.cpp
- src/sdk-reference/cpp/1/kuzzle/constructor/snippets/constructor.cpp
- src/sdk-reference/cpp/1/kuzzle/getters/index.md
- src/sdk-reference/cpp/1/kuzzle/getters/snippets/getters.cpp
- src/sdk-reference/cpp/1/search-result/getters/index.md
- src/sdk-reference/cpp/1/search-result/getters/snippets/getters.cpp
- src/sdk-reference/cpp/1/search-result/getters/snippets/getters.test.yml
- src/sdk-reference/cpp/1/search-result/next/index.md
- src/sdk-reference/cpp/1/search-result/next/snippets/fromsize.cpp
- src/sdk-reference/cpp/1/search-result/next/snippets/scroll.cpp
Update the snippets tests to the latest C++ SDK version, updating the documentation to match all changes made by https://github.com/kuzzleio/sdk-cpp/pull/55 
Namely:
* `document:search` now returns a `std::shared_ptr<SearchResult>` instance, instead of a `SearchResult*` pointer
* `kuzzle:addListener` now takes a shared pointer to a function
* The `Kuzzle` class do not have a `getListeners` getter anymore
* Update the `SearchResult` class getters
* `SearchResult:next` now returns a `std::shared_ptr<SearchResult>` smart pointer
> Update the code snippets to the latest C++ SDK version
