kuzzleio/documentation-V2

plugins/sectionManager.js
plugins/snippetManager.js
scaffolding/lib/common.js
scaffolding/templates/action.cpp.md
scaffolding/templates/action.go.md
scaffolding/templates/action.java.md
scaffolding/templates/action.js.md

This PR add the new template style for the documentation in the scaffolding engine.
- snippet and section files can be kebab-case

Change template + fix scaffodling

---

index.js
plugins/sectionManager.js
src/assets/stylesheets/_config.scss
src/assets/stylesheets/base/_typeset.scss
src/sdk-reference/bulk/import/import.js.md

New page structure (only for bulk import)
https://deploy-preview-21--kuzzle-doc-v2.netlify.com/sdk-reference/bulk/import/
* Fix markdown render
* Fix HBS render in section

Bulk import documentation page

---

src/sdk-reference/index/create/create.cpp.md
src/sdk-reference/index/delete/delete.cpp.md
src/sdk-reference/index/exists/exists.cpp.md
src/sdk-reference/index/get-auto-refresh/getAutoRefresh.cpp.md
src/sdk-reference/index/list/list.cpp.md
src/sdk-reference/index/m-delete/mDelete.cpp.md
src/sdk-reference/index/refresh-internal/refreshInternal.cpp.md
src/sdk-reference/index/refresh/refresh.cpp.md
src/sdk-reference/index/set-auto-refresh/setAutoRefresh.cpp.md
src/sdk-reference/kuzzle/add-listener/add-listener.cpp.md
src/sdk-reference/kuzzle/constructor/constructor.cpp.md
src/sdk-reference/kuzzle/query/query.cpp.md
src/sdk-reference/kuzzle/query/snippets/query.java

Add namespace prefixes `kuzzleio::` in C++ sections (Markdown files)
See [Netlify](https://deploy-preview-24--kuzzle-doc-v2.netlify.com/)

[KZL-372] Add namespace in C++ code parts

---

.travis.yml
package-lock.json
test/lib/runners/javaRunner.js
test/lib/sdk/javaSdk.js
test/lib/snippet.js
test/sdk-versions.yml

Fix Java SDK runner #45
Check travis

Fix Java SDK runner

---

src/assets/stylesheets/layout/_sidebar.scss

Fix nosidebar CSS rule on tablet.
https://deploy-preview-75--kuzzle-doc-v2.netlify.com/sdk-reference/
try it in 768x1024 for example

[CSS] Fix noSidebar rule on tablet

---

test/lib/runners/baseRunner.js

enable regular expressions for expect

enable regular expressions for expect

---

src/api/1/controller-bulk/import/index.md

See https://github.com/kuzzleio/documentation/pull/545

Fix bulk return

---

src/404.md

Add a 404 page
https://deploy-preview-97--kuzzle-doc-v2.netlify.com/404/

[KZL-751] Add 404 page

---

src/sdk-reference/go/1/kuzzle/add-listener/index.md
src/sdk-reference/go/1/kuzzle/add-listener/snippets/add-listener.go

Update addListener SDK documentation for Golang:
* Snippet:
* Update channel type from interface to json.RawMessage.
* Documentation:
* Update signature.
* Update `Arguments` array.
Check Travis.

[fix] Fix kuzzle/addListener snippet and doc

---

src/sdk-reference/js/6/realtime/count/snippets/count.js
src/sdk-reference/js/6/realtime/subscribe/index.md
src/sdk-reference/js/6/realtime/subscribe/snippets/user-notifications.js
src/sdk-reference/js/6/realtime/unsubscribe/snippets/unsubscribe.js
test/sdk-versions.yml

Update JS realtime::subscribe documentation according to BUG KZL-788
depends on https://github.com/kuzzleio/sdk-javascript/pull/332

realtime: updated subscribe documentation according to BUG KZL-788

---

.travis.yml

Waiting tests stop failing, deploy to docs-v2.kuzzle.io on master

[tmp] Deploy to master with failing tests 

---

.ci/comment.html
.travis.yml

:warning: Depends on #117 
Fix Kuttlefish PR reporting
Check kuzzle PR comment

[kuttlefish] Fix PR reporting

---

helpers/ancestryHelpers.js
index.js
src/plugins/1/index.md

Better way to manage redirections, now it's only add a redirect rule to the last children 
https://deploy-preview-120--kuzzle-doc-v2.netlify.com/guide/
fix layout meta on plugin page

[optim] Fix automatic redirect rules

---

src/templates/partials/head.html

Remove site_url from ressource loading in `head` template

[optim] Remove site_url from ressource loading

---

src/assets/stylesheets/extensions/_select2.scss
src/assets/stylesheets/layout/_header.scss
src/assets/stylesheets/layout/_nav.scss
src/templates/partials/navMobile.html
src/templates/sdk.html.hbs

Fix menu on mobile
* Reduce height of top menu (logo and title)
* fix alignment and width of version selector

[CSS] Fix menu on mobile

---

.travis.yml

Remove temporary deployment when tests failed

[ci] Remove unsafe deployment

---

src/assets/stylesheets/base/_typeset.scss
src/assets/stylesheets/extensions/_select2.scss
src/assets/stylesheets/layout/_header.scss
src/assets/stylesheets/layout/_tabs.scss
src/assets/stylesheets/libs/_prism.scss
src/templates/sdk.html.hbs

Various CSS fix :
* realign top menu and left menu
* Fix fonts on code blocks
* Fix selectors align and width

[CSS] Various CSS fix (2)

---

plugins/anchors.js
src/assets/stylesheets/base/_typeset.scss
src/assets/stylesheets/layout/_base.scss
src/assets/stylesheets/layout/_nav.scss
src/guide/1/elasticsearch/basic-queries/index.md
src/guide/1/elasticsearch/bool-query/index.md
src/guide/1/elasticsearch/data-insertion/index.md
src/guide/1/elasticsearch/index.md
src/guide/1/elasticsearch/installation/index.md
src/guide/1/elasticsearch/introduction/index.md
src/guide/1/elasticsearch/useful-commands/index.md
src/templates/partials/anchors.html

Import Elasticsearch cookbook from documentation v1
Goto <https://deploy-preview-136--kuzzle-doc-v2.netlify.com/guide/1/elasticsearch/introduction/>
No rewording done, if needed will be done in another PR to have the diff

elasticsearch: imported documentation from doc v1

---

src/guide/1/datavalidation/fields/index.md
src/guide/1/datavalidation/index.md
src/guide/1/datavalidation/introduction/index.md
src/guide/1/datavalidation/schema/index.md
src/guide/1/datavalidation/validators/index.md

import Data Validation guide
No rewording

KZL-744-import-data-validation-guide

---

src/assets/stylesheets/layout/_tabs.scss
src/templates/partials/tabs.html

Add top menu active behavior
https://deploy-preview-144--kuzzle-doc-v2.netlify.com/guide/1/getting-started/getting-started/

[front] Add top menu active behavior

---

.ci/vfinder/exceptions.txt
.travis.yml

Add Vfinder to check deadlinks in documentation.

[ci] Add Vfinder

---

package-lock.json
src/guide/1/geofencing/go/index.md
src/guide/1/pubsub/go/index.md
src/guide/2/code-examples/geofencing/go/index.md
src/guide/2/code-examples/pubsub/go/index.md
src/sdk-reference/go/1/realtime-notifications/index.md
src/sdk-reference/go/1/realtime/count/snippets/count.go
src/sdk-reference/go/1/realtime/subscribe/index.md
src/sdk-reference/go/1/realtime/subscribe/snippets/document-notifications-leave-scope.go
src/sdk-reference/go/1/realtime/subscribe/snippets/document-notifications.go
src/sdk-reference/go/1/realtime/subscribe/snippets/message-notifications.go
src/sdk-reference/go/1/realtime/subscribe/snippets/user-notifications.go
src/sdk-reference/go/1/realtime/unsubscribe/snippets/unsubscribe.go

Rename KuzzleNotification to NotificationResult in go snippets.

[go] rename type.NotificationResult

---

src/sdk-reference/go/1/error-handling/index.md
src/sdk-reference/go/1/getting-started/index.md
src/sdk-reference/go/1/getting-started/snippets/document.go
src/sdk-reference/go/1/getting-started/snippets/document.test.yml
src/sdk-reference/go/1/getting-started/snippets/init.go
src/sdk-reference/go/1/getting-started/snippets/init.test.yml
src/sdk-reference/go/1/getting-started/snippets/realtime.go
src/sdk-reference/go/1/getting-started/snippets/realtime.test.yml
test/lib/snippet.js
test/lib/testManager.js
test/templates/standalone.tpl.go

Add a getting started section for Go SDK

[KZL-761] Add Golang Getting Started page

---

src/assets/stylesheets/extensions/_permalinks.scss
src/assets/stylesheets/layout/_base.scss
src/assets/stylesheets/layout/_header.scss
src/assets/stylesheets/layout/_sidebar.scss
src/templates/partials/betaChip.html
src/templates/partials/disclaimer.html
src/templates/partials/header.html
src/templates/partials/navMobile.html

This PR fixes the top banner by taking it away. Instead, we added a "beta" chip right next to the page title.
SRSLY.

KZL-945 fix top banner

---

src/assets/js/main.js
src/assets/js/scrollTo.js

Fix scrollTo on left menu and convert to ES6
https://deploy-preview-183--kuzzle-doc-v2.netlify.com/sdk-reference/js/6/ms/get/
* Fix prismJs warning in console

KZL-913 Fix scrollTo on left menu

---

src/sdk-reference/java/1/error-handling/index.md
src/sdk-reference/java/1/getting-started/index.md
src/sdk-reference/java/1/getting-started/snippets/document.java
src/sdk-reference/java/1/getting-started/snippets/document.test.yml
src/sdk-reference/java/1/getting-started/snippets/firstconnection.java
src/sdk-reference/java/1/getting-started/snippets/firstconnection.test.yml
src/sdk-reference/java/1/getting-started/snippets/realtime.java
src/sdk-reference/java/1/getting-started/snippets/realtime.test.yml
test/templates/standalone.tpl.java

It add Java SDK getting started page with tested snippets.
check Travis

[KZL-759] Add Getting started for Java SDK

---

src/guide/1/essentials/installing-console/index.md

Replace link to back-office by console.kuzzle.io

Remove reference to backoffice

---

src/sdk-reference/cpp/1/getting-started/snippets/realtime.cpp
src/sdk-reference/cpp/1/realtime/count/snippets/count.cpp
src/sdk-reference/cpp/1/realtime/subscribe/snippets/document-notifications-leave-scope.cpp
src/sdk-reference/cpp/1/realtime/subscribe/snippets/document-notifications.cpp
src/sdk-reference/cpp/1/realtime/subscribe/snippets/message-notifications.cpp
src/sdk-reference/cpp/1/realtime/subscribe/snippets/user-notifications.cpp
src/sdk-reference/cpp/1/realtime/unsubscribe/snippets/unsubscribe.cpp

Fix C++ realtime tests using new way to declare listeners

[test] Fix C++ realtime tests
